export const TEST_ID = {
    Header: 'header',
    Footer: 'footer',
    Nav: 'nav',
    AppLoader: 'app-loader',
    SearchBlockLoader: 'loader-search-block',
    Breadcrumbs: 'breadcrumbs',
    HeaderLogo: 'header-logo',
    Progress: {
        SignUp: 'sign-up-progress',
    },
    Form: {
        SignIn: 'sign-in-form',
        SignUp: 'sign-up-form',
    },
    Input: {
        Login: 'login-input',
        Password: 'password-input',
        PasswordConfirm: 'confirm-password-input',
        Email: 'email-input',
        FirstName: 'first-name-input',
        LastName: 'last-name-input',
        VerificationCode: 'verification-code-input',
        Search: 'search-input',
    },
    Modal: {
        SignInError: 'sign-in-error-modal',
        SignUpSuccess: 'sign-up-success-modal',
        EmailVerificationFailed: 'email-verification-failed-modal',
        SendEmailModal: 'send-email-modal',
        VerificationCodeModal: 'verification-code-modal',
        ResetCredentialsModal: 'reset-credentials-modal',
        RecipeImageModal: 'recipe-image-modal',
        RecipeImageModalPreviewImage: 'recipe-image-modal-preview-image',
        PreventiveModal: 'recipe-preventive-modal',
    },
    Button: {
        Submit: 'submit-button',
        Repeat: 'repeat-button',
        Close: 'close-button',
        Search: 'search-button',
        Filter: 'filter-button',

        BurgerOpen: 'hamburger-icon',
        BurgerClose: 'close-icon',

        ForgotPassword: 'forgot-password',
        PasswordVisibility: 'password-visibility-button',

        AlergenMenu: 'allergens-menu-button',
        FilterCategory: 'filter-menu-button-категория',
        FindRecipe: 'find-recipe-button',
        AddAlergen: 'add-allergen-button',
        AddOtherAlergen: 'add-other-allergen',
        FilterAlergen: 'allergens-menu-button-filter',
        CloseAlert: 'close-alert-button',
        LoadMore: 'load-more-button',
    },
    Link: {
        Jusiest: 'juiciest-link',
        JusiestMob: 'juiciest-link-mobile',
        Vegan: 'vegan-cuisine',
        ErrorHomePage: 'error-page-go-home',
    },
    Drawer: {
        Filter: 'filter-drawer',
    },
    Card: {
        Food: 'food-card',
        Carousel: 'carousel-card',
    },
    Switch: {
        AlergenSwitcher: 'allergens-switcher',
        AlergenSwitchFilter: 'allergens-switcher-filter',
    },
    Checkbox: {
        Vegan: 'checkbox-веганская кухня',
    },
    Tag: {
        Filter: 'filter-tag',
    },
    Notification: {
        Error: 'error-notification',
    },
    Recipe: {
        Title: 'recipe-title',
        Description: 'recipe-description',
        Categories: 'recipe-categories',
        Time: 'recipe-time',
        Portions: 'recipe-portions',
        Form: 'recipe-form',
        DeleteButton: 'recipe-delete-button',
        SaveDraftButton: 'recipe-save-draft-button',
        PublishButton: 'recipe-publish-recipe-button',
        ImageBlock: 'recipe-image-block',
        AddRecipeButton: 'add-recipe-button',
        ImageBlockInputFile: 'recipe-image-block-input-file',
        ImageBlockPreviewImage: 'recipe-image-block-preview-image',
        AddIngredientsButton: 'recipe-ingredients-add-ingredients',
    },
} as const;
